config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :people

  root 'pages#home'

end

app/models/person.rb
class Person < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def show
    @person = Person.find(params[:id])
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(person_params)
    if @person.save
      redirect_to @person
    else
      render :new
    end
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])
    if @person.update(person_params)
      redirect_to @person
    else
      render :edit
    end
  end

  def destroy
    @person = Person.find(params[:id])
    @person.destroy
    redirect_to root_path
  end

  private

  def person_params
    params.require(:person).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/application/_site_header.html.haml
#site-header
  = link_to t('add politician'), new_person_path
  - if user_signed_in?
    = link_to t('sign out'), destroy_user_session_path, method: :delete
    = link_to current_user.email, ''
  - else
    = link_to t('sign up'), new_user_registration_path
    = link_to t('sign in'), new_user_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title DirectDemocracyAsia
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'site_header'
    %p.notice= notice
    %p.alert= alert
    = yield

app/views/pages/home.html.erb
<h1>Direct Democracy of Asia</h1>
<p>hello democracy, hello asia.</p>

app/views/people/_form.html.haml
= form_for @person do |f|
  .form-group
    = f.label :name
    = f.text_field :name
  .form-group
    = f.label :url
    = f.text_field :url
  .form-group
    = f.label :career
    = f.text_area :career
  .form-group
    = f.label :image
    = f.file_field :image
  .form-group
    = f.submit

app/views/people/edit.html.haml
= render 'form'

app/views/people/new.html.haml
= render 'form'

app/views/people/show.html.haml
%h2= @person.name

- if @person.image.file.present?
  = image_tag @person.image_url(:md)

%p= @person.url

%div= simple_format @person.career

= link_to t('edit'), edit_person_path(@person)
= link_to t('destroy'), @person, method: :delete, data: { confirm: 'are you sure?' }